services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3001}
        VITE_WS_URL: ${VITE_WS_URL:-ws://localhost:8080}
    environment:
      PORT: 80 
    ports:
      - "80:80"
    depends_on:
      - api
      - ws

  api:
    build:
      context: server/api
      dockerfile: Dockerfile.api
    ports:
      - "3001:3001"

  ws:
    build:
      context: server/ws
      dockerfile: Dockerfile.ws
    ports:
      - "8080:8080"
